### ISSUE TITLE
Main Menu Functions Not Firing?

### ISSUE THREAD

**Issue by jjcalo** [joeaugie/soto#6]
It seems that the functions bounded to the main menu items are not firing when we click on the main menu.  Initially I think with the JQTouch library, we would bound a function to the menu list item this way:

```
$('#settings').bind('pageAnimationStart', loadSettings);
$('#viewSessionsPanel').bind('pageAnimationStart', getStudentObservations);
$('#manageStudents').bind('pageAnimationStart', getStudents);
$('#newSessionPanel').bind('pageAnimationStart', initNewSessionsPanel);
```

Maybe now that we're using JQuery Mobile, these lines of code need to be refactored?    Similarly, maybe that's why this line of code is also not working?   I think this should remove the dummy sample hard-coded on the index.html page:

`
$('#manageStudents ul li:gt(0)').remove();
`

**Comment by joeaugie** [comment]
Fixed with lastest commit.
Used .on('click'); instead of .bind();
Used :eq(0) instead of :gt(0)
